import Base
import ./LAWS.bend as Laws

def Laws.fnv1a32_empty():
  {==}

def Laws.fnv1a32_a():
  {==}

def Laws.fnv1a32_foobar():
  {==}

def Laws.fnv1a64_empty():
  {==}

def Laws.fnv1a64_a():
  {==}

def Laws.fnv1a64_foobar():
  {==}

def Laws.xxh32_empty():
  {==}

def Laws.xxh32_a():
  {==}

def Laws.xxh32_abc():
  {==}

def Laws.xxh32_16():
  {==}

def Laws.xxh32_spam():
  {==}

def Laws.xxh32_fox():
  {==}

def Laws.xxh32_seed():
  {==}

def Laws.xxh64_empty():
  {==}

def Laws.xxh64_a():
  {==}

def Laws.xxh64_foobar():
  {==}

def Laws.xxh64_16():
  {==}

def Laws.xxh64_spam():
  {==}

def Laws.xxh64_fox():
  {==}

def Laws.xxh64_seed():
  {==}

def Laws.siphash13_0():
  {==}

def Laws.siphash13_1():
  {==}

def Laws.siphash13_7():
  {==}

def Laws.siphash13_8():
  {==}

def Laws.siphash13_15():
  {==}

def Laws.siphash13_63():
  {==}

def Laws.crc32_empty():
  {==}

def Laws.crc32_hello():
  {==}

def Laws.crc32_fox():
  {==}

def Laws.adler32_empty():
  {==}

def Laws.adler32_hello():
  {==}

def Laws.adler32_fox():
  {==}

def Laws.adler32_ff512():
  {==}

def Laws.crc32_ff512():
  {==}

def Laws.fnv1a32_str():
  {==}

def Laws.fnv1a64_str():
  {==}

def Laws.xxh32_str():
  {==}

def Laws.xxh64_str():
  {==}

def Laws.siphash13_str():
  {==}

def Laws.crc32_str():
  {==}

def Laws.adler32_str():
  {==}
