import Base
import ./LAWS.bend as Laws

def Laws.data():
  {==}

def Laws.headers():
  {==}

def Laws.priority():
  {==}

def Laws.reset():
  {==}

def Laws.settings():
  {==}

def Laws.push():
  {==}

def Laws.ping():
  {==}

def Laws.goaway():
  {==}

def Laws.window():
  {==}

def Laws.continuation():
  {==}

def Laws.data_padded():
  {==}

def Laws.headers_padded_priority():
  {==}

def Laws.push_padded():
  {==}

def Laws.data_stream_zero():
  {==}

def Laws.data_padding_missing():
  {==}

def Laws.data_padding_overrun():
  {==}

def Laws.headers_stream_zero():
  {==}

def Laws.headers_priority_short():
  {==}

def Laws.headers_padding_overrun():
  {==}

def Laws.priority_size():
  {==}

def Laws.priority_stream_zero():
  {==}

def Laws.reset_size():
  {==}

def Laws.reset_stream_zero():
  {==}

def Laws.settings_stream():
  {==}

def Laws.settings_ack_payload():
  {==}

def Laws.settings_size():
  {==}

def Laws.settings_push_value():
  {==}

def Laws.settings_window_value():
  {==}

def Laws.settings_frame_value():
  {==}

def Laws.push_size():
  {==}

def Laws.push_stream_zero():
  {==}

def Laws.push_promised_zero():
  {==}

def Laws.push_padding_overrun():
  {==}

def Laws.ping_size():
  {==}

def Laws.ping_stream():
  {==}

def Laws.goaway_size():
  {==}

def Laws.goaway_stream():
  {==}

def Laws.window_size():
  {==}

def Laws.window_zero():
  {==}

def Laws.continuation_stream():
  {==}

def Laws.oversized():
  {==}

def Laws.oversized_headers():
  {==}

def Laws.partial_payload():
  {==}

def Laws.unknown_type():
  {==}

def Laws.reserved_stream_bit():
  {==}

def Laws.unused_received_flag():
  {==}

def Laws.unused_sent_flag():
  {==}
