import ./LAWS.bend as Laws

def Laws.empty_roundtrip():
  {==}

def Laws.varint_roundtrip():
  {==}

def Laws.uint64_boundary_roundtrip():
  {==}

def Laws.field_number_boundary_roundtrip():
  {==}

def Laws.fixed32_roundtrip():
  {==}

def Laws.fixed64_roundtrip():
  {==}

def Laws.packed_bytes_roundtrip():
  {==}

def Laws.group_roundtrip():
  {==}

def Laws.incomplete_varint():
  {==}

def Laws.overflowing_varint():
  {==}

def Laws.invalid_tag():
  {==}

def Laws.mismatched_group():
  {==}
