#!/usr/bin/env python3
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from generator import generate

sys.stdout.buffer.write(generate(sys.stdin.buffer.read()))
