import Base
import ./LAWS.bend as Laws

def Laws.map_empty():
  {==}

def Laws.map_zero_workers():
  {==}

def Laws.map_one_worker():
  {==}

def Laws.map_uneven():
  {==}

def Laws.map_eight_workers():
  {==}

def Laws.map_more_workers():
  {==}

def Laws.reduce_sum():
  {==}

def Laws.reduce_empty():
  {==}

def Laws.reduce_order():
  {==}

def Laws.map_array():
  {==}

def Laws.map_array_one_worker():
  {==}

def Laws.reduce_array_sum():
  {==}

def Laws.reduce_array_order():
  {==}
