import Base
import ./LAWS.bend as Laws

def Laws.cap():
  {==}

def Laws.random_u32():
  {==}

def Laws.bounded_u32():
  {==}

def Laws.empty_string():
  {==}

def Laws.empty_list():
  {==}

def Laws.empty_bytes():
  {==}

def Laws.zero_size():
  {==}

def Laws.zero_nat():
  {==}

def Laws.shrink_one():
  {==}

def Laws.shrink_nat_one():
  {==}

def Laws.shrink_list_one():
  {==}

def Laws.shrink_maybe_one():
  {==}

def Laws.shrink_byte_one():
  {==}

def Laws.zero_trials():
  {==}

def Laws.char_draw():
  {==}

def Laws.fixed_string():
  {==}

def Laws.fixed_byte():
  {==}

def Laws.bounded_string():
  {==}

def Laws.bounded_bytes():
  {==}

def Laws.bounded_list():
  {==}

def Laws.fixed_list():
  {==}

def Laws.maybe_draw():
  {==}

def Laws.map_draw():
  {==}

def Laws.bind_draw():
  {==}

def Laws.pair_draw():
  {==}

def Laws.shrink_char():
  {==}

def Laws.shrink_string():
  {==}

def Laws.first_failure():
  {==}
