#!/usr/bin/env python3
"""Write width.bend from the pinned UCD. Run from anywhere: python3 tty/gen.py"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "unicode"))
import gen  # noqa: E402  (unicode/gen.py: pinned version, cache, Tree, ranges)

EAW = "EastAsianWidth.txt"
ZERO_GC = {"Mn", "Me", "Cf", "Cc", "Zl", "Zp"}


def eaw():
    """code point -> East_Asian_Width, @missing defaults first (unassigned CJK is W)."""
    path = os.path.join(gen.CACHE, EAW)
    if not os.path.exists(path):
        urllib.request.urlretrieve(f"https://www.unicode.org/Public/{gen.VERSION}/ucd/{EAW}", path)
    out = {}
    for m in re.finditer(r"^# @missing: ([0-9A-F]+)\.\.([0-9A-F]+); (\w+)", open(path).read(), re.M):
        for c in range(int(m[1], 16), int(m[2], 16) + 1):
            out[c] = m[3]
    out.update({c: v[0] for c, v in gen.props(EAW).items()})
    return out


def main():
    gen.fetch()
    gc, _, _ = gen.unicode_data()
    ea = eaw()
    ri = set(range(0x1F1E6, 0x1F200))

    # Columns for a code point that starts a grapheme cluster. Ambiguous (A) is narrow.
    # Soft hyphen shows; Hangul medial vowels and final consonants join the syllable.
    def w(c):
        if c == 0xAD:
            return 1
        if gc.get(c, "Cn") in ZERO_GC or 0x1160 <= c <= 0x11FF or 0xD7B0 <= c <= 0xD7FF:
            return 0
        if ea.get(c, "N") in ("W", "F") or c in ri:
            return 2
        return 1

    cols = {c: w(c) for c in range(0x110000)}
    body = gen.Tree("w", ["c"], "c", "U32").emit(
        gen.ranges(lambda c: str(cols[c]), [c for c in cols if cols[c] != 1], "1"), "w")
    with open(os.path.join(HERE, "width.bend"), "w") as out:
        out.write(f"# Generated by gen.py from UCD {gen.VERSION}. Do not edit.\nimport Base\n{body}")


if __name__ == "__main__":
    main()
