import Base
import ./f64.bend as F
import ./LAWS.bend as Laws

def Laws.add_tie():
  {==}

def Laws.add_overflow():
  {==}

def Laws.add_subnormal():
  {==}

def Laws.add_cancel():
  {==}

def Laws.add_neg_zero():
  {==}

def Laws.mul_round():
  {==}

def Laws.mul_neg_zero():
  {==}

def Laws.div_third():
  {==}

def Laws.div_by_zero():
  {==}

def Laws.div_zero_zero():
  {==}

def Laws.inf_minus_inf():
  {==}

def Laws.nan_add():
  {==}

def Laws.eq_signed_zero():
  {==}

def Laws.nan_not_eq():
  {==}

def Laws.lt_sign():
  {==}

def Laws.from_u32():
  {==}

def Laws.is_subnormal():
  {==}
