import Base
import ./LAWS.bend as Laws

def Laws.enc_startup():
  {==}

def Laws.enc_ssl_request():
  {==}

def Laws.enc_password():
  {==}

def Laws.enc_sasl_initial():
  {==}

def Laws.enc_sasl_response():
  {==}

def Laws.enc_parse():
  {==}

def Laws.enc_bind():
  {==}

def Laws.enc_describe():
  {==}

def Laws.enc_execute():
  {==}

def Laws.enc_sync():
  {==}

def Laws.enc_close():
  {==}

def Laws.enc_terminate():
  {==}

def Laws.rt_startup():
  {==}

def Laws.rt_ssl_request():
  {==}

def Laws.rt_password():
  {==}

def Laws.rt_sasl_initial():
  {==}

def Laws.rt_sasl_response():
  {==}

def Laws.rt_parse():
  {==}

def Laws.rt_bind():
  {==}

def Laws.rt_describe():
  {==}

def Laws.rt_execute():
  {==}

def Laws.rt_sync():
  {==}

def Laws.rt_close():
  {==}

def Laws.rt_terminate():
  {==}

def Laws.dec_front_trailing():
  {==}

def Laws.dec_front_bad_kind():
  {==}

def Laws.enc_auth_ok():
  {==}

def Laws.enc_auth_sasl():
  {==}

def Laws.enc_row_description():
  {==}

def Laws.enc_data_row():
  {==}

def Laws.enc_error():
  {==}

def Laws.rt_auth_ok():
  {==}

def Laws.rt_auth_cleartext():
  {==}

def Laws.rt_auth_sasl():
  {==}

def Laws.rt_auth_sasl_continue():
  {==}

def Laws.rt_auth_sasl_final():
  {==}

def Laws.dec_auth_md5():
  {==}

def Laws.rt_parameter_status():
  {==}

def Laws.rt_backend_key_data():
  {==}

def Laws.rt_ready_for_query():
  {==}

def Laws.rt_row_description():
  {==}

def Laws.rt_row_description_empty():
  {==}

def Laws.rt_data_row():
  {==}

def Laws.rt_command_complete():
  {==}

def Laws.rt_error():
  {==}

def Laws.rt_notice():
  {==}

def Laws.rt_parse_complete():
  {==}

def Laws.rt_bind_complete():
  {==}

def Laws.rt_close_complete():
  {==}

def Laws.rt_no_data():
  {==}

def Laws.rt_empty_query():
  {==}

def Laws.rt_portal_suspended():
  {==}

def Laws.rt_other():
  {==}

def Laws.notice_get():
  {==}

def Laws.dec_want_header():
  {==}

def Laws.dec_want_body():
  {==}

def Laws.dec_short_length():
  {==}

def Laws.dec_huge_length():
  {==}

def Laws.dec_bad_status():
  {==}

def Laws.dec_no_nul():
  {==}

def Laws.dec_trailing():
  {==}

def Laws.dec_col_overrun():
  {==}

def Laws.dec_col_negative():
  {==}

def Laws.dec_notice_unterminated():
  {==}

def Laws.split_session():
  {==}

def Laws.split_rows():
  {==}
