import Base
import ./LAWS.bend as Laws

def Laws.rt_simple():
  {==}

def Laws.rt_error():
  {==}

def Laws.rt_int_zero():
  {==}

def Laws.rt_int_minus_one():
  {==}

def Laws.rt_int_max():
  {==}

def Laws.rt_int_min():
  {==}

def Laws.rt_bulk():
  {==}

def Laws.rt_bulk_empty():
  {==}

def Laws.rt_array():
  {==}

def Laws.rt_null():
  {==}

def Laws.rt_true():
  {==}

def Laws.rt_false():
  {==}

def Laws.rt_double():
  {==}

def Laws.rt_bignum():
  {==}

def Laws.rt_bulk_error():
  {==}

def Laws.rt_verbatim():
  {==}

def Laws.rt_dict():
  {==}

def Laws.rt_dict_empty():
  {==}

def Laws.rt_set():
  {==}

def Laws.rt_attr():
  {==}

def Laws.rt_push():
  {==}

def Laws.enc_nested():
  {==}

def Laws.enc_command():
  {==}

def Laws.enc_dict_odd():
  {==}

def Laws.enc_attr_even():
  {==}

def Laws.enc_line_crlf():
  {==}

def Laws.enc_verbatim_format():
  {==}

def Laws.dec_resp2_nulls():
  {==}

def Laws.dec_int_overflow():
  {==}

def Laws.dec_int_min():
  {==}

def Laws.dec_next():
  {==}

def Laws.dec_bad_type():
  {==}

def Laws.dec_bad_length():
  {==}

def Laws.dec_bad_digit():
  {==}

def Laws.split_small():
  {==}

def Laws.split_resp2():
  {==}

def Laws.prefix_small():
  {==}

def Laws.prefix_resp2():
  {==}
